add_library(vkexec_private_headers INTERFACE)
target_include_directories(vkexec_private_headers INTERFACE "${PROJECT_SOURCE_DIR}/src")

add_subdirectory(vkexec)
add_subdirectory(vkexec_features)
add_subdirectory(vkexec_graphics)
add_subdirectory(vkexec_extensions)
if(vkexec_BUILD_TOOLS)
  add_subdirectory(vkexec_tools)
endif()
